# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'EmployeeRecord' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmployeeRecord
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'DropDown'
  pod 'Moya', '~> 12.0'
  pod 'ObjectMapper', '~> 3.4'
  pod 'TSMessages', :git => 'https://github.com/KrauseFx/TSMessages.git'
  pod 'FTIndicator'
  pod 'RealmSwift'

  target 'EmployeeRecordTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EmployeeRecordUITests' do
    # Pods for testing
  end

end
